<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.5
Pandas:  1.0.5


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:'C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv'
bikes = pd.read_table('C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [4]:
#ANSWER:
bikes= pd.read_table('C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv', header = 0, delimiter = ',')


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [5]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [6]:
df = pd.read_excel('C://Users/monic/Desktop/data science -insitute of dat/Iris.xls', sheet_name = 'Data')##, usecols=['Species_No', 'Petal_width'])
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [7]:
df = pd.read_excel('C://Users/monic/Desktop/data science -insitute of dat/Iris.xls', sheet_name = 'Data', usecols=['Species_No', 'Petal_width'])
df

Species_No  Petal_width
0             1          0.2
1             1          0.2
2             1          0.2
3             1          0.2
4             1          0.2
..          ...          ...
145           3          2.3
146           3          1.9
147           3          2.0
148           3          2.3
149           3          1.8

[150 rows x 2 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [8]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df
##df.head()

time   latitude   longitude      depth   mag magType  \
0  2020-09-23T02:21:26.970Z  19.210501 -155.378998  30.860001  2.47      ml   
1  2020-09-23T02:05:27.820Z  17.944800  -67.109600   9.000000  3.21      md   

   nst  gap    dmin   rms  ...                   updated  \
0   53  158     NaN  0.13  ...  2020-09-23T02:27:01.740Z   
1   22  238  0.0616  0.11  ...  2020-09-23T02:33:07.195Z   

                                  place        type horizontalError  \
0             10 km E of Pāhala, Hawaii  earthquake            0.56   
1  7 km WSW of La Parguera, Puerto Rico  earthquake            0.68   

  depthError  magError  magNst     status  locationSource magSource  
0       0.68      1.68      27  automatic              hv        hv  
1       0.39      0.25      20   reviewed              pr        pr  

[2 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [9]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

[                             Bank Name           City  ST   CERT  \
 0                 The First State Bank  Barboursville  WV  14361   
 1                   Ericson State Bank        Ericson  NE  18265   
 2     City National Bank of New Jersey         Newark  NJ  21111   
 3                        Resolute Bank         Maumee  OH  58317   
 4                Louisa Community Bank         Louisa  KY  58112   
 ..                                 ...            ...  ..    ...   
 556                 Superior Bank, FSB       Hinsdale  IL  32646   
 557                Malta National Bank          Malta  OH   6629   
 558    First Alliance Bank & Trust Co.     Manchester  NH  34264   
 559  National State Bank of Metropolis     Metropolis  IL   3815   
 560                   Bank of Honolulu       Honolulu  HI  21029   
 
                    Acquiring Institution       Closing Date  
 0                         MVB Bank, Inc.      April 3, 2020  
 1             Farmers and Merchants Bank  F

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [10]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [12]:
df = pd.read_csv('C://Users/monic/Desktop/data science -insitute of dat/bikeshare.csv')
df

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3   
1               0           1  0.22  0.2727  0.80     0.0000       8   
2               0           1  0.22  0.2727  0.80     0.0000       5   
3               0           1  0.24  0.2879  0.75     0.0000       3   
4               0           1  0.24  0.2879  0.75     0.0000       0   
...           ...         ...   ...     ...   ...        ...     ...   
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
0              13   16  
1              32   40  
2              27   32  
3              10   13  
4               1    1  
...           ...  ...  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49  

[17379 rows x 17 columns]

In [13]:
#ANSWER 17379 rows × 17 columns


What are the column names in `bikes`?

In [14]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [15]:
#ANSWER instant	dteday	season	yr	mnth	hr	holiday	weekday	workingday	weathersit	temp	atemp	hum	windspeed	casual	registered	cnt


What are the data types of these columns?

In [16]:
df.dtypes


instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [17]:
df.index


RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [18]:
df['season']


0        1
1        1
2        1
3        1
4        1
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64

In [19]:
df[['season']]

season
0           1
1           1
2           1
3           1
4           1
...       ...
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

How would we use object notation to show the first 4 rows of `atemp`?

In [20]:
print(df['atemp'].head(4))


0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64


Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [21]:
##df[[0]]
##df[0]
df[0,0]
#E: bikes[[0,0]]

KeyError: (0, 0)

What is the correct way to access the 1st row of the DataFrame by its index?

In [24]:
df[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

In [23]:
df.iloc[:1, :]


instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [22]:
df.iloc[:, 1:2]

dteday
0      2011-01-01
1      2011-01-01
2      2011-01-01
3      2011-01-01
4      2011-01-01
...           ...
17374  2012-12-31
17375  2012-12-31
17376  2012-12-31
17377  2012-12-31
17378  2012-12-31

[17379 rows x 1 columns]

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [ ]:
df.isnull().head()

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [ ]:
##df.isnull().sum()
##pd.isnull(df).sum()
n = pd.isnull(df)
df[n].count()

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [80]:
pd.isnull(df).sum()


instant        0
dteday         0
season         0
yr             0
mnth           0
hr             0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed      0
casual         0
registered     0
cnt            0
atemp_level    0
dtype: int64

##What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid. not a number, missing value

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [ ]:
#ANSWER
##df.replace(np.nan,0)
def divide (num,denom):
    try:
        return num/denom
    except:
        return "error"

In [ ]:
divide(8,3)

Apply the Pandas `isna` function to the following data objects:

In [26]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [27]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [28]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [29]:
#ANSWER
print(pd.isna(array))

[[False  True False]
 [False False  True]]


How is the pandas I/O parameter `na_values` used?

? ANSWER: For converting special characters to NaN.

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [30]:
df['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [31]:
#ANSWER
#ANSWER
print('instant:', df['instant'].min(), 'to', df['instant'].max())
print('dteday:', df['dteday'].min(), 'to', df['dteday'].max())
print('windspeed:', df['windspeed'].min(), 'to', df['windspeed'].max())

instant: 1 to 17379
dteday: 2011-01-01 to 2012-12-31
windspeed: 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [32]:
df_min, df_max = (min(df.min(numeric_only=True)), max(df.max(numeric_only=True)))
df_min, df_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [33]:
df['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [34]:
#ANSWER
df['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [35]:
type(bikes['atemp'])

pandas.core.series.Series

In [36]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
14317    14318  2012-08-24       3   1     8  18        0        5   
15554    15555  2012-10-15       4   1    10   7        0        1   
6158      6159  2011-09-19       3   0     9   4        0        1   
16448    16449  2012-11-23       4   1    11   2        0        5   
8946      8947  2012-01-13       1   1     1  15        0        5   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
14317           1           2  0.72  0.6818  0.62     0.1940     109   
15554           1           2  0.58  0.5455  0.68     0.3284      15   
6158            1           2  0.50  0.4848  0.77     0.1642       2   
16448           1           1  0.26  0.2879  0.75     0.0896       1   
8946            1           1  0.26  0.2121  0.33     0.5821      15   

       registered  cnt  
14317         627  736  
15554         461  476  
6158            6    8  
16448           4    5  
8946          123  138

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [37]:
atemp_level = pd.cut(df['atemp'], bins = 4)         

In [40]:
print(atemp_level)

0        (0.25, 0.5]
1        (0.25, 0.5]
2        (0.25, 0.5]
3        (0.25, 0.5]
4        (0.25, 0.5]
            ...     
17374    (0.25, 0.5]
17375    (0.25, 0.5]
17376    (0.25, 0.5]
17377    (0.25, 0.5]
17378    (0.25, 0.5]
Name: atemp, Length: 17379, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]


What is `atemp_level`?

In [38]:
#ANSWER
print(type(atemp_level))  

<class 'pandas.core.series.Series'>


Here is a random sample of `atemp_level`:

In [39]:
atemp_level.sample(5)          

4855     (0.5, 0.75]
11402    (0.25, 0.5]
6081     (0.25, 0.5]
14733    (0.25, 0.5]
11597    (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [41]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

5150      hot
16886    mild
5673     warm
17284    cool
14738    mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [46]:
#ANSWER
df['atemp_level'] = atemp_level
df[(df.atemp_level=='mild')&(df.season ==2)].atemp_level.count()

1829

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [47]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)# array cration numpy.arange([start, ]stop, [step, ], dtype=None) 
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [48]:
print(a)
print(b)
print(c)
print(d)

[0. 0. 0.]
[[1. 1. 1.]]
[[[5 1 8 8]
  [4 7 3 4]
  [3 7 7 1]]

 [[5 6 1 4]
  [2 9 5 1]
  [2 6 1 6]]]
[0 1 2 3]


In [ ]:
# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [3]:
rock = pd.read_csv('C://Users/monic/Desktop/data science -insitute of dat/DATA/rock.csv')

## Check Column Names

Check column names and clean.

In [4]:
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [5]:
rock['COMBINED']=rock['COMBINED'].str.lower()
rock['COMBINED']

0                         caught up in you by .38 special
1                             fantasy girl by .38 special
2                          hold on loosely by .38 special
3                   rockin' into the night by .38 special
4                               art for arts sake by 10cc
                              ...                        
2225                    she loves my automobile by zz top
2226                          tube snake boogie by zz top
2227                                       tush by zz top
2228                                 tv dinners by zz top
2229    waitin' for the bus/jesus just left chicago by...
Name: COMBINED, Length: 2230, dtype: object

In [18]:
def new_column_names(column_names):
    new_column_name = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        new_column_name.append(c)    
    return new_column_name        

In [21]:
rock.columns = new_column_names(rock.columns)
print(rock.columns)

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')


# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [8]:
rock.isnull().sum()

Song Clean        0
ARTIST CLEAN      0
Release Year    577
COMBINED          0
First?            0
Year?             0
PlayCount         0
F*G               0
dtype: int64

In [25]:
print(rock['release_year'].replace(np.nan,0))


0       1982
1          0
2       1981
3       1980
4       1975
        ... 
2225       0
2226    1981
2227    1975
2228    1983
2229    1973
Name: release_year, Length: 2230, dtype: object


In [26]:
rock.isnull().sum()

song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64

In [27]:
##rock['Release Year'][rock['Release Year'].isnull()]=0


In [28]:
null_mask = rock['release_year'].isnull()
rock.loc[null_mask, 'release_year'] = 0

In [29]:
rock.isnull().sum()

song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [119]:
rock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Song Clean    2230 non-null   object 
 1   ARTIST CLEAN  2230 non-null   object 
 2   Release Year  2230 non-null   object 
 3   COMBINED      2230 non-null   object 
 4   First?        2230 non-null   int64  
 5   Year?         2230 non-null   int64  
 6   PlayCount     2230 non-null   int64  
 7   F*G           2230 non-null   int64  
 8   release_year  0 non-null      float64
dtypes: float64(1), int64(4), object(4)
memory usage: 156.9+ KB


# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [34]:
def check_min_max(df):
    # Check min, max of each column
    print(df.describe().T[['min', 'max']])


In [35]:
check_min_max(rock)

           min    max
first      1.0    1.0
year       0.0    1.0
playcount  0.0  142.0
fg         0.0  142.0


In [32]:
# mask to find all rows with SONGFACTS.COM
song_facts_mask = rock['release_year'] == 'SONGFACTS.COM'
rock.loc[song_facts_mask, 'release_year'] = np.NaN
rock['release_year'].value_counts() 


0       577
1973    104
1975     83
1977     83
1970     81
1971     75
1969     72
1980     70
1978     64
1979     63
1981     61
1967     61
1983     60
1976     56
1982     54
1984     51
1972     50
1974     48
1968     46
1985     39
1987     39
1986     37
1991     34
1989     32
1966     30
1988     29
1965     28
1994     25
1990     22
1993     19
1992     14
1964     14
1999     13
1995     10
1963      9
1996      9
1997      9
2002      6
1998      6
2012      5
2004      5
2005      5
2001      4
2000      3
2008      3
2003      3
2007      3
2011      3
1962      3
2014      2
2013      2
1955      1
1961      1
1071      1
1958      1
2006      1
Name: release_year, dtype: int64

# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [36]:
def check_song(row):
    print('Song: ', row['song_clean'])
    print('Artist: ', row['artist_clean'])
    print('Released before 1970: ', row['release_year'] < 1970)
    print('\n')

In [37]:
#Chech the function for any row
check_song(rock.iloc[0])

Song:  Caught Up in You
Artist:  .38 Special


TypeError: '<' not supported between instances of 'str' and 'int'

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [ ]:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

## Apply these functions to your dataset

In [ ]:
rock.apply(convert_to_float)

## Describe the new float-only DataFrame.

In [ ]:
rock.describe().T



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



